### ISSUE TITLE
Namespace of JSON loaded data

### ISSUE THREAD

**Issue by alebedev87** [open-policy-agent/kube-mgmt#59] opened 2020-01-16 14:24 UTC
Hello,

I'm using the external data loaded from a ConfigMap labeled `openpolicyagent.org/data=opa`.
README.md says that I need to know the namespace of this ConfigMap when I try to access its data from a policy: `data.<ns>.<key>`.

I have 2 questions about this:

- What is the best way to get the namespace where I put the data ConfigMap? (Workaround I found: use `opa.runtime()` which gives me all the environment variables of OPA and then make OPA container consume the namespace using the downwardAPI).
- Can the data ConfigMap be created in other namespaces (not OPA's one) like policies (`--policies` flag)?

Kube-mgmt version being used: 0.10

Thank you,
Andrey

**Comment by tsandall** [comment] 2020-01-21 15:12
> What is the best way to get the namespace where I put the data ConfigMap? (Workaround I found: use opa.runtime() which gives me all the environment variables of OPA and then make OPA container consume the namespace using the downwardAPI)

I suspect that users are hardcoding the namespace in their policies today. @iverberk do you have any thoughts on this?

> Can the data ConfigMap be created in other namespaces (not OPA's one) like policies (--policies flag)?

yes, the namespaces specified by `--policies` will get used.

**Comment by iverberk** [comment] 2020-01-22 16:05
We are indeed hardcoding the namespace because we know where we will put the data configmap beforehand. I don't have any other suggestions on how to do it dynamically unfortunately.

**Comment by tsandall** [comment] 2020-01-29 01:42
I'm going to close this because I don't think there's anything to be done at this point in time.

**Closed by tsandall** 2020-01-29 01:42 UTC
Labels: question

**Comment by freegroup** [comment] 2020-10-20 08:11
the issue is closed but maybe worth to discuss.

we use our policies in different environments like CloudFoundry, K8S, simple EC2 Instances and the developer, which generates the rego files, should not care about the landscape where the rego files are deployed.

From my point of view referencing the namespace and config-map name in the rego files is not a good pattern. You are mixing deployment and rules.
