### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by pieterv-icloud-com** [open-policy-agent/kube-mgmt#69] opened 2020-05-21 19:08 UTC
I tried deploying opa using helm on a Rancher k3s cluster running on a number of Raspberry Pis. 

The deployment fails with an "exec format error" message

opa only supports the amd64 architecture, not the arm/v6 architecture.

**Comment by eshepelyuk** [comment] 2022-05-06 20:29
Duplicate of #143

**Closed by eshepelyuk** 2022-05-06 20:29 UTC
